/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/app';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './app.css.shim';
import * as import11 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '../../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/router/src/router_outlet_map';
import * as import17 from '@angular/core/src/linker/component_factory_resolver';
import * as import18 from '@angular/router/src/directives/router_link';
import * as import19 from '@angular/router/src/directives/router_outlet';
import * as import20 from '@angular/core/src/security';
export class Wrapper_App {
  context:import0.App;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.App();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_App_Host:import2.RenderComponentType = (null as any);
class _View_App_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _App_0_4:Wrapper_App;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_App_Host0,renderType_App_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('hn-app',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_App0(this.viewUtils,this.injector(0),this._appEl_0);
    this._App_0_4 = new Wrapper_App();
    this._appEl_0.initComponent(this._App_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._App_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.App) && (0 === requestNodeIndex))) { return this._App_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._App_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_App_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_App_Host === (null as any))) { (renderType_App_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_App_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppNgFactory:import9.ComponentFactory<import0.App> = new import9.ComponentFactory<import0.App>('hn-app',viewFactory_App_Host0,import0.App);
const styles_App:any[] = [import10.styles];
var renderType_App:import2.RenderComponentType = (null as any);
class _View_App0 extends import1.AppView<import0.App> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _RouterLinkWithHref_4_3:import11.Wrapper_RouterLinkWithHref;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _RouterLinkWithHref_9_3:import11.Wrapper_RouterLinkWithHref;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _RouterLinkWithHref_12_3:import11.Wrapper_RouterLinkWithHref;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import11.Wrapper_RouterLinkWithHref;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import11.Wrapper_RouterLinkWithHref;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _RouterOutlet_28_5:import12.Wrapper_RouterOutlet;
  _text_29:any;
  _text_30:any;
  _arr_0:any;
  /*private*/ _expr_2:any;
  _arr_1:any;
  /*private*/ _expr_5:any;
  _arr_2:any;
  /*private*/ _expr_8:any;
  _arr_3:any;
  /*private*/ _expr_11:any;
  _arr_4:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_App0,renderType_App,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','header');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','inner');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'a',(null as any));
    this._RouterLinkWithHref_4_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this.renderer.setElementAttribute(this._el_6,'alt','logo');
    this.renderer.setElementAttribute(this._el_6,'class','logo');
    this.renderer.setElementAttribute(this._el_6,'src','./assets/logo.png');
    this._text_7 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._el_9 = this.renderer.createElement(this._el_2,'a',(null as any));
    this._RouterLinkWithHref_9_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_10 = this.renderer.createText(this._el_9,'Home',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_12 = this.renderer.createElement(this._el_2,'a',(null as any));
    this._RouterLinkWithHref_12_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_13 = this.renderer.createText(this._el_12,'Top',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_2,'a',(null as any));
    this._RouterLinkWithHref_15_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_16 = this.renderer.createText(this._el_15,'Best',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_2,'a',(null as any));
    this._RouterLinkWithHref_18_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_19 = this.renderer.createText(this._el_18,'New',(null as any));
    this._text_20 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_21 = this.renderer.createElement(this._el_2,'a',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','github');
    this.renderer.setElementAttribute(this._el_21,'href','https://github.com/vuejs/vue-hackernews-2.0');
    this.renderer.setElementAttribute(this._el_21,'target','_blank');
    this._text_22 = this.renderer.createText(this._el_21,'\n          Built with Angular2\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_26 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','view');
    this._text_27 = this.renderer.createText(this._el_26,'\n	',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'router-outlet',(null as any));
    this._appEl_28 = new import3.AppElement(28,26,this,this._el_28);
    this._RouterOutlet_28_5 = new import12.Wrapper_RouterOutlet(this.parentInjector.get(import16.RouterOutletMap),this._appEl_28.vcRef,this.parentInjector.get(import17.ComponentFactoryResolver),(null as any));
    this._text_29 = this.renderer.createText(this._el_26,'\n',(null as any));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._arr_1 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._arr_2 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._arr_3 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    this._arr_4 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_14 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.RouterLinkWithHref) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._RouterLinkWithHref_4_3.context; }
    if (((token === import18.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3.context; }
    if (((token === import18.RouterLinkWithHref) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._RouterLinkWithHref_12_3.context; }
    if (((token === import18.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3.context; }
    if (((token === import18.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._RouterLinkWithHref_18_3.context; }
    if (((token === import19.RouterOutlet) && (28 === requestNodeIndex))) { return this._RouterOutlet_28_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this._arr_0('');
    this._RouterLinkWithHref_4_3.check_routerLink(currVal_1,throwOnChange,false);
    this._RouterLinkWithHref_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_4:any = this._arr_1('top');
    this._RouterLinkWithHref_9_3.check_routerLink(currVal_4,throwOnChange,false);
    this._RouterLinkWithHref_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_7:any = this._arr_2('top');
    this._RouterLinkWithHref_12_3.check_routerLink(currVal_7,throwOnChange,false);
    this._RouterLinkWithHref_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    const currVal_10:any = this._arr_3('best');
    this._RouterLinkWithHref_15_3.check_routerLink(currVal_10,throwOnChange,false);
    this._RouterLinkWithHref_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_13:any = this._arr_4('new');
    this._RouterLinkWithHref_18_3.check_routerLink(currVal_13,throwOnChange,false);
    this._RouterLinkWithHref_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    this._RouterOutlet_28_5.detectChangesInternal(this,this._el_28,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = this._RouterLinkWithHref_4_3.context.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_4,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._RouterLinkWithHref_9_3.context.href;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_9,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_8:any = this._RouterLinkWithHref_12_3.context.href;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_12,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._RouterLinkWithHref_15_3.context.href;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_15,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_11));
      this._expr_11 = currVal_11;
    }
    const currVal_14:any = this._RouterLinkWithHref_18_3.context.href;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_18,'href',this.viewUtils.sanitizer.sanitize(import20.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_4_3.context.ngOnDestroy();
    this._RouterLinkWithHref_9_3.context.ngOnDestroy();
    this._RouterLinkWithHref_12_3.context.ngOnDestroy();
    this._RouterLinkWithHref_15_3.context.ngOnDestroy();
    this._RouterLinkWithHref_18_3.context.ngOnDestroy();
    this._RouterOutlet_28_5.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_4_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_9_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_12_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_15_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_18_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_App0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.App> {
  if ((renderType_App === (null as any))) { (renderType_App = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_App,{})); }
  return new _View_App0(viewUtils,parentInjector,declarationEl);
}