/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../app/feed-view/item.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './item.component.css.shim';
export class Wrapper_ItemView {
  context:import0.ItemView;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.ItemView();
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ItemView_Host:import2.RenderComponentType = (null as any);
class _View_ItemView_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ItemView_0_4:Wrapper_ItemView;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ItemView_Host0,renderType_ItemView_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('item-view',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ItemView0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemView_0_4 = new Wrapper_ItemView();
    this._appEl_0.initComponent(this._ItemView_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ItemView_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ItemView) && (0 === requestNodeIndex))) { return this._ItemView_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ItemView_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ItemView_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ItemView_Host === (null as any))) { (renderType_ItemView_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ItemView_Host0(viewUtils,parentInjector,declarationEl);
}
export const ItemViewNgFactory:import9.ComponentFactory<import0.ItemView> = new import9.ComponentFactory<import0.ItemView>('item-view',viewFactory_ItemView_Host0,import0.ItemView);
const styles_ItemView:any[] = [import10.styles];
var renderType_ItemView:import2.RenderComponentType = (null as any);
class _View_ItemView0 extends import1.AppView<import0.ItemView> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ItemView0,renderType_ItemView,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'item view',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_ItemView0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ItemView> {
  if ((renderType_ItemView === (null as any))) { (renderType_ItemView = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_ItemView,{})); }
  return new _View_ItemView0(viewUtils,parentInjector,declarationEl);
}