/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['[_nghost-%COMP%] {\n	background-color: #fff;\n	padding: 20px 30px 20px 80px;\n	border-bottom: 1px solid #eee;\n	position: relative;\n	line-height: 20px;\n}\n\n[_nghost-%COMP%]   .score[_ngcontent-%COMP%] {\n	color: #f60;\n	font-size: 1.1em;\n	font-weight: 700;\n	position: absolute;\n	top: 50%;\n	left: 0;\n	width: 80px;\n	text-align: center;\n	margin-top: -10px;\n}\n\n[_nghost-%COMP%]   .meta[_ngcontent-%COMP%], [_nghost-%COMP%]   .host[_ngcontent-%COMP%] {\n	font-size: 0.85em;\n	color: #999;\n}\n\n[_nghost-%COMP%]   .meta[_ngcontent-%COMP%]   a[_ngcontent-%COMP%], [_nghost-%COMP%]   .host[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n	color: #999;\n	text-decoration: underline;\n}\n\n[_nghost-%COMP%]   .meta[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover, [_nghost-%COMP%]   .host[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\n	color: #f60;\n}'];